//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.1.1
//     from Assets/Scripts/Input/InputPlayerMaster.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @InputPlayerMaster : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @InputPlayerMaster()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""InputPlayerMaster"",
    ""maps"": [
        {
            ""name"": ""Player"",
            ""id"": ""40582a32-0f47-4f3f-b35f-8626fb85b061"",
            ""actions"": [
                {
                    ""name"": ""VelocityPress"",
                    ""type"": ""Button"",
                    ""id"": ""f01a1027-f2d5-49f9-9774-c4fb37e68c7a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""VelocityHold"",
                    ""type"": ""Button"",
                    ""id"": ""459513d2-eaa8-425e-8b06-8858851aca89"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""VelocityRelease"",
                    ""type"": ""Button"",
                    ""id"": ""931c5290-4248-4e04-9828-3eb6d16f27c4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""8fd1c5e4-d5bd-452b-8e3a-059e56478f2d"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""VelocityPress"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c847d822-9b90-405a-a474-44962f0a4415"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": ""Hold"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""VelocityHold"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c3284420-1418-4602-8142-03275185fd7c"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": ""Press(behavior=1)"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""VelocityRelease"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Player
        m_Player = asset.FindActionMap("Player", throwIfNotFound: true);
        m_Player_VelocityPress = m_Player.FindAction("VelocityPress", throwIfNotFound: true);
        m_Player_VelocityHold = m_Player.FindAction("VelocityHold", throwIfNotFound: true);
        m_Player_VelocityRelease = m_Player.FindAction("VelocityRelease", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Player
    private readonly InputActionMap m_Player;
    private IPlayerActions m_PlayerActionsCallbackInterface;
    private readonly InputAction m_Player_VelocityPress;
    private readonly InputAction m_Player_VelocityHold;
    private readonly InputAction m_Player_VelocityRelease;
    public struct PlayerActions
    {
        private @InputPlayerMaster m_Wrapper;
        public PlayerActions(@InputPlayerMaster wrapper) { m_Wrapper = wrapper; }
        public InputAction @VelocityPress => m_Wrapper.m_Player_VelocityPress;
        public InputAction @VelocityHold => m_Wrapper.m_Player_VelocityHold;
        public InputAction @VelocityRelease => m_Wrapper.m_Player_VelocityRelease;
        public InputActionMap Get() { return m_Wrapper.m_Player; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerActions set) { return set.Get(); }
        public void SetCallbacks(IPlayerActions instance)
        {
            if (m_Wrapper.m_PlayerActionsCallbackInterface != null)
            {
                @VelocityPress.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnVelocityPress;
                @VelocityPress.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnVelocityPress;
                @VelocityPress.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnVelocityPress;
                @VelocityHold.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnVelocityHold;
                @VelocityHold.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnVelocityHold;
                @VelocityHold.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnVelocityHold;
                @VelocityRelease.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnVelocityRelease;
                @VelocityRelease.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnVelocityRelease;
                @VelocityRelease.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnVelocityRelease;
            }
            m_Wrapper.m_PlayerActionsCallbackInterface = instance;
            if (instance != null)
            {
                @VelocityPress.started += instance.OnVelocityPress;
                @VelocityPress.performed += instance.OnVelocityPress;
                @VelocityPress.canceled += instance.OnVelocityPress;
                @VelocityHold.started += instance.OnVelocityHold;
                @VelocityHold.performed += instance.OnVelocityHold;
                @VelocityHold.canceled += instance.OnVelocityHold;
                @VelocityRelease.started += instance.OnVelocityRelease;
                @VelocityRelease.performed += instance.OnVelocityRelease;
                @VelocityRelease.canceled += instance.OnVelocityRelease;
            }
        }
    }
    public PlayerActions @Player => new PlayerActions(this);
    public interface IPlayerActions
    {
        void OnVelocityPress(InputAction.CallbackContext context);
        void OnVelocityHold(InputAction.CallbackContext context);
        void OnVelocityRelease(InputAction.CallbackContext context);
    }
}
